### ISSUE TITLE
Newly added stream data is not collected for known device types on known hubs

### ISSUE THREAD

**Issue by kevinswiber** [zettajs/zetta-device-data-collection#1]
Because we only wire up the event listeners once, new streams on known device types associated with previously known hubs do not get a subscription.  We need to dispose the subscription when the peer disconnects.  I'll attempt a PR soon.

**Comment by kevinswiber** [comment]
We don't even look at the streams if the hub has already connected: https://github.com/zettajs/zetta-device-data-collection/blob/6ed4e05b95358fc53fcaa41f752aa43d4815097a/collection.js#L21-L23

**Comment by kevinswiber** [comment]
This also represents a fairly serious memory leak.

**Comment by AdamMagaluk** [comment]
@kevinswiber The memory leak is definitely an issue. We should probably move the stream collections to use the new stream methods with wildcards, they weren't out yet when this was written.

I'm thinking for every hub that connect's we send a subscription for `**`, then we would need a way to get that data to the zetta app, may need to use some undocumented apis. This approach would get us away from instantiating a `virtual_device` for each device.
